services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: sgr_frontend
    restart: always
    ports:
      - "85:80"
    networks:
      - sgr_frontend_net

networks:
  sgr_frontend_net:
    driver: bridge
